# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99318003c729a6fbb130347ef50d97b5ac8eb55d6314c398428d5116ab468e24b1218850fcb85f6fd37bff6a8b9316a22ba2bc651c27c2ded9482f6895a85952

test:
  secret_key_base: 36f34a98ce0b4267ad8f57c2cd2230a46d397dc0d09976fc6b073ebc417fa4a0c9ffaab8602fe240f9a56f4448e19f1d825520fd71669600056aaf06bfc28315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
